simv: romsim.v
	vcs -full64 +lint=TFIPC-L +lint=PCWM romsim.v -y /opt/Xilinx/Vivado/2016.2/data/verilog/src/retarget +libext+.v -y /opt/Xilinx/Vivado/2016.2/data/verilog/src/unisims +libext+.v /opt/Xilinx/Vivado/2016.2/data/verilog/src/glbl.v |& tee logfile
